### PR TITLE
add support for `file` attribute on `testcase`

### PR DESCRIPTION
**Pull request by kaplanelad**
Hey, 
For gitlab pipeline integration in need `file` attribute on tesstcase

### CODE REVIEW

**Comment by kaplanelad** [comment]
Fixed fmt test

**Comment by bachp** [comment]
@kaplanelad Do you have a link to a documentation where this attribute is defined? This will be helpful for future reference.

**Comment by kaplanelad** [comment]
Hey @bachp,
I didn't find an official guide (not for the `file` attribute and not for any JUnit other fields)
But, you can take a look at the GitLab  unit reports sourceCode
https://gitlab.com/gitlab-org/gitlab/-/blob/master/spec/fixtures/junit/junit.xml
https://gitlab.com/gitlab-org/gitlab/-/blob/master/spec/fixtures/junit/junit_with_three_testsuites_2.xml

I took generated JUnit file (junit-report-rs) and just added the `file`, and it workes

**Comment by kaplanelad** [comment]
Thanks @bachp, 
any option to bump a new version to crates?

**Comment by bachp** [comment]
@kaplanelad Yes I'm planning to do this later today. It's still manual as I didn't have time to automate this via github actions

**Pull request merged**
